### ISSUE TITLE
Profile Dependency Error

### ISSUE THREAD

**Issue by karikarshivani** [mitre/k8s-node-stig-baseline#1]
When I run the baseline, I get the following error:
![Screen Shot 2022-12-06 at 11 04 14 AM](https://user-images.githubusercontent.com/11844975/205962081-9480cc40-3b7a-41b9-af6e-9fef7c779a8f.png)

What fixed it for me was adding the optional branch tag to [inspec.yml](https://github.com/mitre/k8s-node-stig-baseline/blob/main/inspec.yml#L15-L17):
```
depends:
  - name: inspec-k8s-node
    git: https://github.com/mitre/inspec-k8s-node.git
    branch: main
```

Please lmk if I'm missing anything.
